version: '3'

services:
  db:
    container_name: psql
    image: postgres
    networks:
      - psql-pgql
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - psql-pgql
    stdin_open: true
    tty: true
  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/postgres # To be moved to environment file
    expose:
      - 5000
    ports:
      - 5000:5000
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--port", "5000",
              "--schema", "public", "--enhance-graphiql", "-w", "--cors"]
    links:
      - db
    networks:
      - psql-pgql
networks:
  psql-pgql:
