# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverageingredients',
            options={'verbose_name_plural': 'beverage ingredients'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'quantities'},
        ),
        migrations.AddField(
            model_name='beverage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='directions',
            field=models.TextField(null=True),
        ),
    ]
