# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingredient_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='divisor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
