# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-22 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190922_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
