# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190304_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_garnish',
            field=models.BooleanField(default=False),
        ),
    ]
