# Generated by Django 2.2.5 on 2020-09-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190922_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
