# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190304_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='attribution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='glassware',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
