# Generated by Django 2.2.5 on 2020-10-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201006_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
    ]
