# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190309_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='tools',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
