# Generated by Django 2.2.5 on 2020-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ingredient_is_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shortlist',
            field=models.BooleanField(default=False),
        ),
    ]
