# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_beverage_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
