# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_beverage_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeverageIngredients',
            new_name='RecipeIngredients',
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'recipe ingredients'},
        ),
        migrations.AddField(
            model_name='beverage',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
