# Generated by Django 2.2.5 on 2020-10-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_shortlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='parent',
        ),
        migrations.CreateModel(
            name='IngredientToIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='api.Ingredient')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='api.IngredientToIngredient', to='api.Ingredient'),
        ),
    ]
