# Generated by Django 2.2.5 on 2020-10-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201011_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
