# Generated by Django 2.2.5 on 2020-10-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_recipe_non_alcoholic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='generous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quantity',
            name='scant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together={('amount', 'divisor', 'unit', 'scant', 'generous')},
        ),
    ]
