# Generated by Django 2.2.5 on 2020-11-01 18:58
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201025_0043'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
