# Generated by Django 2.2.5 on 2020-11-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201101_1858'),
    ]

    operations = [
        migrations.RunSQL('CREATE TEXT SEARCH CONFIGURATION english_unaccent( COPY = english );'),
        migrations.RunSQL('ALTER TEXT SEARCH CONFIGURATION english_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, english_stem'),
    ]
