# Generated by Django 2.2.5 on 2020-11-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201101_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_garnish',
            field=models.BooleanField(default=False),
        ),
    ]
