# Generated by Django 2.2.5 on 2020-11-04 00:42

from django.db import migrations


def load_data(apps, schema_editor):
    Ingredient = apps.get_model('api', 'Ingredient')
    RecipeIngredient = apps.get_model('api', 'RecipeIngredient')

    garnish_ingredients = Ingredient.objects.filter(is_garnish=True)

    for ingredient in garnish_ingredients:
        RecipeIngredient.objects.filter(ingredient=ingredient).update(
            is_garnish=ingredient.is_garnish)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_recipeingredient_is_garnish'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
