# Generated by Django 2.2.5 on 2020-11-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201104_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
