# Generated by Django 2.2.5 on 2021-03-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_recipe_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='partner_likes',
            field=models.BooleanField(default=False),
        ),
    ]
